feat(ProductView) ProductView according to there user's role
atlp-rwanda/champs-ec-fe pull request #13
Opened 2024-05-31 16:23 UTC by k3lly003

### What does this PR do?
This PR allow a user to be able to view products (one & all)
### Description of Task to be completed?
- This task's tests
- storybook
- viewing single products for both Seller and user/client
### How should this be manually tested?
The test's are not yet implemented
### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2698211/stories/187300196

2024-06-10 07:59 UTC, sabatohura approved these changes

2024-06-10 08:00 UTC, sabatohura requested changes
Fix circleci

2024-06-18 13:15 UTC, Eli250 requested changes

2024-06-18 13:15 UTC, Eli250 commented on src/components/ProductList.tsx
> +                className="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gra
Why are all these codes duplicated? You can put them in loop if they have similar properties.

2024-06-20 08:52 UTC, kayigmb approved these changes

2024-06-20 10:23 UTC, kayigmb approved these changes

2024-06-20 10:24 UTC, tchamianest approved these changes

2024-06-20 10:55 UTC, Eli250 approved these changes

2024-06-20 10:57 UTC, merged