##187504942: Test for signup page
atlp-rwanda/champs-ec-fe pull request #16
Opened 2024-06-02 19:59 UTC by tchamianest

#### What does this PR do?
Testing signup page and also hook 
#### Description of Task to be completed?
test for signup page and also test the hooks 
#### How should this be manually tested?
- npm run test
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?
[#187504942]( https://www.pivotaltracker.com/n/projects/2698211)

2024-06-02 20:01 UTC, kayigmb approved these changes

2024-06-02 20:06 UTC, emmanueltct approved these changes

2024-06-03 13:38 UTC, Eli250 requested changes

2024-06-03 13:38 UTC, Eli250 commented on src/hooks/useSignup.ts
>      window.location.href = '/auth/login';
Use 'useRouter' hook from next-navigation to handle client routing.

2024-06-04 12:19 UTC, Eli250 approved these changes

2024-06-04 12:19 UTC, merged