add two factor authentication for seller
atlp-rwanda/champs-ec-fe pull request #17
Opened 2024-06-03 07:57 UTC by emmanueltct

#### What does this PR do?
this PR implements task related to pivot story of Seller two factor authentication
#### Description of Task to be completed?
When the user signed in as a seller he/she will be prompted with an interface to verify OTP  received on email to be authenticated
#### How should this be manually tested?
 this feature will be tested locally by cloning this project or you can test it online using deployed link for vercel preview
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/story/show/187300194
#### Screenshots (if appropriate)
![otp verification](https://github.com/atlp-rwanda/champs-ec-fe/assets/34351692/ae04b9f2-7d94-4fe8-8589-d2ae16dbfc3d)

2024-06-03 08:36 UTC, tchamianest approved these changes

2024-06-03 08:37 UTC, tchamianest approved these changes

2024-06-04 19:02 UTC, kayigmb approved these changes

2024-06-06 07:55 UTC, PrinceRWIGIMBA approved these changes

2024-06-06 09:28 UTC, denislohan requested changes
You did not follow our naming conventions
1. branch naming
2. commit naming
3. the description does not explain well how to test

2024-06-06 10:49 UTC, closed without merging