ft(google-login): Add google login feature #187300191
atlp-rwanda/champs-ec-fe pull request #19
Opened 2024-06-05 06:34 UTC by sabatohura

#### What does this PR do?

- Implement Google authentication on frontend

#### Description of Task to be completed?

- Google Login
- Generating user token
- Store user token in session storage

#### How should this be manually tested?
- App login with Google
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2698211/stories/187300191

2024-06-06 13:16 UTC, tchamianest approved these changes

2024-06-06 13:57 UTC, denislohan requested changes
PR title is wrong

2024-06-06 14:34 UTC, sabatohura commented
> PR title is wrong

let re-work on it, Thanks

2024-06-06 14:35 UTC, kayigmb approved these changes

2024-06-06 14:44 UTC, sabatohura commented
> PR title is wrong

fixed

2024-06-06 15:58 UTC, Eli250 requested changes

2024-06-06 17:51 UTC, Eli250 requested changes

2024-06-06 17:51 UTC, Eli250 commented on .env
> -NEXT_PUBLIC_URL=https://champs-ec-be.onrender.com/api
This file should not be pushed

2024-06-07 13:35 UTC, Eli250 approved these changes

2024-06-07 15:05 UTC, merged