feat(password Reset):Users should be presented with reset password link
atlp-rwanda/champs-ec-fe pull request #23
Opened 2024-06-07 12:03 UTC by janet-barbie

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2024-06-12 16:10 UTC, PrinceRWIGIMBA approved these changes

2024-06-12 16:44 UTC, kanu-cast approved these changes

2024-06-12 17:45 UTC, Eli250 requested changes

2024-06-12 17:45 UTC, Eli250 commented on .env
> +# NEXT_PUBLIC_URL=https://champs-ec-be.onrender.com/api
@janet-barbie delete this file.

2024-06-13 13:52 UTC, kanu-cast approved these changes

2024-06-13 14:29 UTC, Eli250 approved these changes

2024-06-13 15:05 UTC, merged