#187300189 Configure storybook for component development
atlp-rwanda/champs-ec-fe pull request #4
Opened 2024-05-24 12:20 UTC by janet-barbie

#### What does this PR do?
StoryBook configuration
#### Description of Task to be completed?
Configure the storybook tool to make the working on related components more efficient, easier to reuse and have better component documentation.
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2698211

2024-05-24 12:45 UTC, k3lly003 approved these changes

2024-05-24 13:23 UTC, tchamianest approved these changes

2024-05-26 14:07 UTC, Eli250 requested changes

2024-05-26 14:07 UTC, Eli250 commented on src/stories/button.css
> +  font-family: 'Nunito Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
Use tailwind for instead of pure css. The css files are not necessary

2024-05-26 14:07 UTC, Eli250 commented on src/stories/header.css
> +  font-family: 'Nunito Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
Get rid of this file and use tailwing instead

2024-05-26 14:07 UTC, Eli250 commented on src/stories/page.css
> +  font-family: 'Nunito Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
Use tailwind instead

2024-05-28 10:06 UTC, Eli250 requested changes

2024-05-28 10:06 UTC, Eli250 commented on lib/tailwind.css
> +.btn {
We already have tailwind configuration file, why are you recreating it here?

2024-05-28 10:06 UTC, Eli250 commented on lib/Button/Button.tsx
> +import React, { ReactNode } from 'react'
Components should be under components directory unless it is a special pattern required from storybook.

2024-05-28 14:08 UTC, merged