seller and admin dashboard
atlp-rwanda/champs-ec-fe pull request #46
Opened 2024-06-27 21:27 UTC by tchamianest

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2024-07-06 13:07 UTC, kayigmb approved these changes

2024-07-08 14:56 UTC, Eli250 requested changes
Resolve all feedback.

2024-07-08 14:56 UTC, Eli250 commented on src/app/(profile)/profile-edit/page.tsx
> -"use client";
This endpoint `src/app/(profile)/profile-edit/...` does not not follow our naming conventions. It has to be something close to `.../profile/[profileId]`.

2024-07-08 14:56 UTC, Eli250 commented on src/app/(profile)/profile-edit/page.tsx
> +          console.log('currentProfile', currentProfile);
Remove these consoles.

2024-07-08 14:56 UTC, Eli250 commented on src/app/(profile)/profile-edit/page.tsx
> +              <ul className="hidden md:block text-sm space-y-2">
This file is too long. You are probably not using reusable components. Refactor this component by dividing it into smaller components that perform specific tasks.

2024-07-08 14:56 UTC, Eli250 commented on src/app/dashboard/addproduct/page.tsx
> +'use client';
We have never accepted this endpoint (`src/app/dashboard/addproduct/page.tsx`). You need to revise our naming conventions.

2024-07-08 14:56 UTC, Eli250 commented on src/app/dashboard/home/page.tsx
> +'use client';
Why can't you just use `/dashboard`. The home is not needed.

2024-07-08 14:56 UTC, Eli250 commented on src/app/dashboard/product_/[id]/page.tsx
> +import React, { useEffect, useState } from 'react';
This page endpoint is wrong, and I have mentioned this several times.

2024-07-08 14:56 UTC, Eli250 commented on src/app/dashboard/product_/[id]/page.tsx
> +      const responsecat: any = await request.get(`/products/${productId}`);
Do not use `any`

2024-07-08 14:56 UTC, Eli250 commented on src/components/2faVerification.tsx
> +      router.push('/dashboard/home');
`/dashboard/home` endpoint does not make sense.

2024-07-08 14:56 UTC, Eli250 commented on src/components/EditProfile.tsx
> +
This component is too long. You have to rafactor it.

2024-07-09 16:04 UTC, merged